const teamAbbr = {
    "Arizona Cardinals": "ARI", 
    "Atlanta Falcons": "ATL", 
    "Baltimore Ravens": "BAL", 
    "Buffalo Bills": "BUF", 
    "Carolina Panthers": "CAR", 
    "Chicago Bears": "CHI", 
    "Cincinnati Bengals": "CIN", 
    "Cleveland Browns": "CLE", 
    "Dallas Cowboys": "DAL", 
    "Denver Broncos": "DEN", 
    "Detroit Lions": "DET", 
    "Green Bay Packers": "GNB", 
    "Houston Texans": "HOU", 
    "Indianapolis Colts": "IND", 
    "Jacksonville Jaguars": "JAX", 
    "Kansas City Chiefs": "KAN", 
    "Los Angeles Chargers": "LAC", 
    "Los Angeles Rams": "LAR", 
    "Las Vegas Raiders": "LVR", 
    "Miami Dolphins": "MIA", 
    "Minnesota Vikings": "MIN", 
    "New England Patriots": "NWE", 
    "New Orleans Saints": "NOR", 
    "New York Giants":"NYG",
    "New York Jets":"NYJ", 
    "Philadelphia Eagles":"PHI", 
    "Pittsburgh Steelers":"PIT", 
    "Seattle Seahawks":"SEA", 
    "San Francisco 49ers":"SFO", 
    "Tampa Bay Buccaneers":"TAM", 
    "Tennessee Titans":"TEN", 
    "Washington Commanders":"WAS"
};

export default teamAbbr;
