version: '3.8'

services:
  # PostgreSQL - Use Cloud SQL in production instead
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Flask App
  flask-app:
    build:
      context: ./Backend/FlaskApp
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0

  # Spring Boot App
  spring-app:
    build:
      context: ./Backend/nfl-zone
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

  # React App
  frontend:
    build:
      context: ./Frontend/nfl-fantasy-frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8082:8080"
    depends_on:
      - spring-app
      - flask-app

volumes:
  postgres_data:
